WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75b321b040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e1872a38dcd6512227cfce6703fa25fd/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75b3219d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e1872a38dcd6512227cfce6703fa25fd/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75b3219ae0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e1872a38dcd6512227cfce6703fa25fd/window