WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e136d300>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/31a43731aeefbe9791fd0af471b8b648/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e136ed40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/31a43731aeefbe9791fd0af471b8b648/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e136e1d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/31a43731aeefbe9791fd0af471b8b648/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e132c580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1d927c190d9adb24f6045f98c06b3c87/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e132c9d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1d927c190d9adb24f6045f98c06b3c87/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e132dc60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1d927c190d9adb24f6045f98c06b3c87/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e12717b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a571a88f74a1bce2b41be5c3bd1d1964/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e1271090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a571a88f74a1bce2b41be5c3bd1d1964/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e1270760>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a571a88f74a1bce2b41be5c3bd1d1964/window