{"uid":"23ee84ff5302f3bd","name":"User is able to change country code","fullName":"tests.test_login.TestLogin#test_country_code_change","historyId":"d4789fa5b9353700b289a8b501933add","time":{"start":1683399697230,"stop":1683399697230,"duration":0},"description":"User is able to change country code","descriptionHtml":"<p>User is able to change country code</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: Service /github/home/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127","statusTrace":"request = <SubRequest 'setup' for <Function test_country_code_change[country_code_data1-chrome]>>\nbrowser = 'chrome'\n\n    @pytest.fixture(scope=\"function\")\n    def setup(request: pytest.FixtureRequest, browser):\n        if (browser in (\"chrome\")):\n            chrome_options = webdriver.ChromeOptions()\n            chrome_options.set_capability(\n                \"goog:loggingPrefs\", {\"browser\": \"ALL\"}\n            )\n    \n        match browser:\n            case \"chrome\":\n                chrome_options.headless = True\n>               driver = webdriver.Chrome(service=ChromeService(\n                    ChromeDriverManager().install()), options=chrome_options)\n\ntests/conftest.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__\n    super().__init__(\n../home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__\n    self.service.start()\n../home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/common/service.py:100: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7ff822b1ae90>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /github/home/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127\n\n../home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/common/service.py:113: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setup","time":{"start":1683399697231,"stop":1683399697745,"duration":514},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: Service /github/home/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127\n\n","statusTrace":"  File \"/github/home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/github/home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/github/home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/github/workspace/tests/conftest.py\", line 38, in setup\n    driver = webdriver.Chrome(service=ChromeService(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/github/home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/github/home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 101, in __init__\n    self.service.start()\n  File \"/github/home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 100, in start\n    self.assert_process_still_running()\n  File \"/github/home/.local/share/virtualenvs/workspace-0SZQOxG8/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 113, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"a32bfd6aa06d"},{"name":"thread","value":"9-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'chrome'"},{"name":"country_code_data","value":"{'country': 'Albania', 'code': '+355'}"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["@pytest.mark.usefixtures('setup')"]},"source":"23ee84ff5302f3bd.json","parameterValues":["'chrome'","{'country': 'Albania', 'code': '+355'}"]}