WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc24732f20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f69a26933f9c877d53d0df7504086782/se/log
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc247329b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f69a26933f9c877d53d0df7504086782/se/log
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc24730a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f69a26933f9c877d53d0df7504086782/se/log
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc25aa4fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f69a26933f9c877d53d0df7504086782/se/log
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc25aa53c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f69a26933f9c877d53d0df7504086782/se/log
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc25aa6350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f69a26933f9c877d53d0df7504086782/se/log